BlockNesting:
  Max: 5

ClassLength:
  Max: 198

CyclomaticComplexity:
  Max: 8

FileName:
  Exclude:
    - lib/lita-locker.rb

MethodLength:
 Max: 40

GuardClause:
  Exclude:
    - lib/lita/handlers/locker.rb

PerceivedComplexity:
  Max: 12

LineLength:
  Max: 120

AbcSize:
  Enabled: false
