FileName:
  Exclude:
    - lib/lita-locker.rb

LineLength:
  Max: 120

AbcSize:
  Exclude:
    - lib/lita/handlers/locker_misc.rb
  Max: 30

MethodLength:
  Max: 17
  Exclude:
    - lib/lita/handlers/locker_misc.rb

PerceivedComplexity:
  Exclude:
    - lib/lita/handlers/locker_misc.rb
