ClassLength:
  Max: 103

CyclomaticComplexity:
  Max: 7

FileName:
  Exclude:
    - lib/lita-locker.rb

MethodLength:
 Max: 31

PerceivedComplexity:
  Max: 12

LineLength:
  Max: 120

AbcSize:
  Max: 49
