BlockNesting:
  Max: 5

ClassLength:
  Max: 500

CyclomaticComplexity:
  Max: 10

Documentation:
  Exclude:
    - lib/lita/handlers/locker.rb

FileName:
  Exclude:
    - lib/lita-locker.rb

MethodLength:
  Max: 200

GuardClause:
  Exclude:
    - lib/lita/handlers/locker.rb
